### ISSUE TITLE
Possible bug in 'parallel' package

### ISSUE THREAD

**Issue by SMW69** [clementfarabet/lua---parallel#5]
Hi,
I posted a question on Torch google group.
Here is it again

require 'parallel'
code = [=[
         require 'torch'
         t = torch.Tensor(10)
         print(t)
]=]

c = parallel.fork()
c:exec(code)

When I run c = parallel.fork() I get "sh: 1: torch-lua: not found" warning but process object is created.
When I run c:exec(code) it never returns.

It was recommended to open an issue.

**Comment by nicholas-leonard** [comment]
This should be closed.
